"""Продажи: оплаты (Stars и заказы с сайта), промокоды, коды активации, журнал согласий, права доступа.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('products', sa.String(length=32), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('list_amount', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('telegram_charge_id', sa.String(length=128), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=128), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('activation_code', sa.String(length=24), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('offer_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_code'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('telegram_charge_id')
    )
    op.create_index(op.f('ix_purchases_provider_charge_id'), 'purchases', ['provider_charge_id'], unique=False)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('doc_version', sa.String(length=16), nullable=False),
    sa.Column('doc_sha256', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.add_column('enrollments', sa.Column('freezes_per_week', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('enrollments', sa.Column('access', sa.String(length=16), nullable=True))
    op.add_column('enrollments', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_enrollments_purchase', 'enrollments', 'purchases', ['purchase_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('source', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('promo_code', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('run_credits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('subscription_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_kind', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('subscription_recurring', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('sub_reminded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('star_sub_charge_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'star_sub_charge_id')
    op.drop_column('users', 'sub_reminded_at')
    op.drop_column('users', 'subscription_recurring')
    op.drop_column('users', 'subscription_kind')
    op.drop_column('users', 'subscription_until')
    op.drop_column('users', 'run_credits')
    op.drop_column('users', 'promo_code')
    op.drop_column('users', 'source')
    op.drop_constraint('fk_enrollments_purchase', 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'purchase_id')
    op.drop_column('enrollments', 'access')
    op.drop_column('enrollments', 'freezes_per_week')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_provider_charge_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
